export enum ICustomerActionTypes {
  GET_CUSTOMERS_SUCCESSFUL = 'CUSTOMER/GET_CUSTOMERS_SUCCESSFUL',
  GET_CUSTOMERS_FAILED = 'CUSTOMER/GET_CUSTOMERS_FAILED',
  GET_CUSTOMER_SUCCESSFUL = 'CUSTOMER/GET_CUSTOMER_SUCCESSFUL',
  GET_CUSTOMER_FAILED = 'CUSTOMER/GET_CUSTOMER_FAILED',
  EDIT_CUSTOMER_SUCCESSFUL = 'CUSTOMER/EDIT_CUSTOMER_SUCCESSFUL',
  EDIT_CUSTOMER_FAILED = 'CUSTOMER/EDIT_CUSTOMER_FAILED',
  CREATE_CUSTOMER_SUCCESSFUL = 'CUSTOMER/CREATE_CUSTOMER_SUCCESSFUL',
  CREATE_CUSTOMER_FAILED = 'CUSTOMER/CREATE_CUSTOMER_FAILED',
  DELETE_CUSTOMER_SUCCESSFUL = 'CUSTOMER/DELETE_CUSTOMER_SUCCESSFUL',
  DELETE_CUSTOMER_FAILED = 'CUSTOMER/DELETE_CUSTOMER_FAILED',
  CUSTOMERS_IS_LOADING = 'CUSTOMER/CUSTOMERS_IS_LOADING',
}

// TODO: add fields for customer object
export type ICustomerState = {
  customers: [] | null;
  customer: object | null;
  error: string | null;
  isLoading: boolean;
};

export type ICustomerActionCreator = {
  type: string;
  payload: ICustomerState;
};
